name: Deploy to Server

on:
  push:
    branches:
      - main  # 원하는 브랜치를 지정합니다.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy via SCP with password
      run: |
        scp -r /github/workspace/AdelaideInside/* $USERNAME@$SERVER:/root/aidev
  
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}  # FTP 서버 주소를 Secrets에서 가져와 환경 변수로 설정합니다.
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}  # FTP 사용자 이름을 Secrets에서 가져와 환경 변수로 설정합니다.
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}  # FTP 비밀번호를 Secrets에서 가져와 환경 변수로 설정합니다.

    - name: Restart Docker container  # Docker 컨테이너를 재시작합니다.
      run: docker restart DevAI
