name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print current directory
      run: pwd

    - name: List files
      run: ls -la

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy via SCP with password
      run: |
        echo "Current directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        sshpass -p ${{ secrets.FTP_PASSWORD }} scp -o StrictHostKeyChecking=no -r /home/runner/work/${{ github.repository }}/$(basename ${{ github.repository }})/* ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }}:/aidev
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

    - name: Restart Docker container
      run: sshpass -p ${{ secrets.FTP_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} "docker restart DevAI"
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.F
