name: Deploy(Production)
on:
  push:
    branches:
      - main  # 원하는 브랜치를 지정합니다.

jobs:
  deploy-production:
    needs: deploy-dev  # 다른 워크플로우(job)가 완료된 후에 실행됩니다.
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Production deployment
        run: echo 'production deployment'