name: Deploy to Production server
on:
  push:
    branches:
      - main  # 원하는 브랜치를 지정합니다.


jobs:
  production:
    runs-on: ubuntu-latest

    environment: production

    steps:
       - uses: actions/checkout@v2
       - run: echo 'production deployment'